
  name: waver
  version: '1.3.1'
  summary: Data over sound
  description: |
    Waver allows you to send and receive text messages from nearby devices through sound waves.

  base: core18
  grade: stable
  confinement: strict

  parts:
    alsa-mixin:
      plugin: dump
      source: https://github.com/diddlesnaps/snapcraft-alsa.git
      source-subdir: snapcraft-assets
      build-packages:
        - libasound2-dev
      stage-packages:
        - libasound2
        - libasound2-plugins
        - yad

    waver:
      source: https://github.com/ggerganov/ggwave
      source-type: git
      plugin: cmake
      plugin: dump
      source: .
      build-packages:
        - g++
        - make
        - libsdl2-dev
      stage-packages:
        - libsdl2-2.0-0
        - libgl1
        - libglx0
        - libglu1-mesa
        - libgl1-mesa-dri
      after: [alsa-mixin]

  apps:
    waver:
      command-chain: ["snap/command-chain/alsa-launch"]
      command: build/bin/waver
      plugs: [unity7, opengl, alsa, audio-playback, audio-record, network, network-bind]

  environment:
    ALWAYS_USE_PULSEAUDIO: '1'
